name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          cd /home/ubuntu/ics-dashboard
          git pull
          sudo docker compose up -d --build